apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qqgk4hiua-go-gitops
  description: This is GitOps manifest for qqgk4hiua-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=qqgk4hiua-go
    backstage.io/kubernetes-id: qqgk4hiua-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qqgk4hiua-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qqgk4hiua-go
